LITRevu/LITRevu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("flux/", include(("blog.urls", "blog"), namespace="flux")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LITRevu/blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.flux, name="flux"),
    path("posts/", views.posts, name="posts"),
    path("create_ticket/", views.create_ticket, name="create-ticket"),
    path("create_review/", views.create_review, name="create-review"),
    path("update_ticket/<int:ticket_id>/", views.update_ticket, name="update-ticket"),
    path("delete_ticket/<int:ticket_id>/", views.delete_ticket, name="delete-ticket"),
    path("delete_review/<int:review_id>/", views.delete_review, name="delete-review"),
    path("update_review/<int:review_id>/", views.update_review, name="update-review"),
    path("search_user/", views.search_user, name="search-user"),
    path("subscriptions/", views.subscriptions, name="subscriptions"),
    path("subscribe/<int:user_id>/", views.subscribe_user, name="subscribe"),
    path("unsubscribe/<int:user_id>/", views.unsubscribe_user, name="unsubscribe"),
    path("response_review/<int:ticket_id>/", views.response_review, name="response-review"),
]

LITRevu/blog/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.


class Ticket(models.Model):
    title = models.CharField(max_length=128, verbose_name="Title")
    description = models.TextField(
        max_length=2048, blank=True, verbose_name="Description"
    )
    image = models.ImageField(
        null=True, blank=True, verbose_name="Image", upload_to="images/"
    )

    time_created = models.DateTimeField(auto_now_add=True, verbose_name="Time created")
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title


class Review(models.Model):
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        # validates that rating must be between 0 and 5
        validators=[MinValueValidator(0), MaxValueValidator(5)]
    )
    headline = models.CharField(max_length=128, verbose_name="Titre")
    body = models.TextField(max_length=8192, blank=True, verbose_name="Commentaire")
    time_created = models.DateTimeField(auto_now_add=True, verbose_name="Time created")

    def __str__(self) -> str:
        return self.headline


class UserFollows(models.Model):
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="following"
    )
    followed_user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="followed_by",
    )

    class Meta:
        unique_together = ("user", "followed_user")

LITRevu/blog/forms.py
from django import forms
from django.urls import reverse_lazy
from . import models


class TicketForm(forms.ModelForm):
    class Meta:
        model = models.Ticket
        fields = ["title", "description", "image"]
        success_url = reverse_lazy("blog:flux")


class ReviewForm(forms.ModelForm):
    class Meta:
        model = models.Review
        fields = ["headline", "body", "rating"]
        success_url = reverse_lazy("blog:flux")

    # Set rating field to not required
    rating = forms.IntegerField(
        required=False,
        widget=forms.RadioSelect(choices=[(i, str(i)) for i in range(6)]),
    )


class FollowUserForm(forms.ModelForm):
    class Meta:
        model = models.UserFollows
        fields = "__all__"
        success_url = reverse_lazy("blog:subscriptions")

LITRevu/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from . import forms
from itertools import chain
from authentication.models import User
from .models import Ticket, Review, UserFollows
from django.contrib import messages
from django.core.paginator import Paginator


@login_required
def flux(request):
    # Get the list of users that the logged-in user is following
    followed_users = request.user.following.all().values_list('followed_user', flat=True)

    # Filter tickets and reviews separately
    flux_ticket = Ticket.objects.filter(user__in=followed_users) | Ticket.objects.filter(user=request.user)
    flux_review = Review.objects.filter(user__in=followed_users) | Review.objects.filter(ticket__user=request.user)

    # Combine the QuerySets into a single list
    combined_data = list(chain(flux_ticket, flux_review))

    # Sort the combined data by time_created
    combined_data.sort(key=lambda instance: instance.time_created, reverse=True)

    p = Paginator(combined_data, 4)
    page_number = request.GET.get("page")
    page = p.get_page(page_number)

    context = {
        "page": page,
    }

    return render(request, "blog/flux.html", context)


@login_required
def posts(request):
    # Filter the Ticket and Review objects for the currently logged-in user
    posts_ticket = Ticket.objects.filter(user=request.user)
    posts_review = Review.objects.filter(user=request.user)
    show_critiques = True
    show_tickets = False

    combined_data = sorted(
        chain(posts_ticket, posts_review),
        key=lambda instance: instance.time_created,
        reverse=True,
    )

    p = Paginator(combined_data, 4)
    # Get the current page number from the query parameter 'page'
    page_number = request.GET.get("page")

    # Paginate the filtered ticket and review data
    page = p.get_page(page_number)

    context = {
        "page": page,
        "show_critiques": show_critiques,
        "show_tickets": show_tickets,
    }

    return render(request, "blog/posts.html", context)


@login_required
def create_ticket(request):
    if request.method == "POST":
        # Create an instance of the ticket form with the submitted data
        form = forms.TicketForm(request.POST, request.FILES)
        if form.is_valid():
            ticket = form.save(commit=False)
            # Set the user for the ticket
            ticket.user = request.user
            ticket.save()

            messages.success(request, "Ticket créé avec succès.")

            return redirect("blog:flux")
        else:
            messages.error(
                request,
                "Erreur lors de la création du ticket. Veuillez vérifier le formulaire.",
            )
    else:
        # If the request is a GET request (the user is loading the page),
        # create an instance of an empty ticket form
        form = forms.TicketForm()

    # Pass the ticket form to the template
    context = {
        "form": form,
    }

    return render(request, "blog/create_ticket.html", context)


@login_required
def create_review(request):
    if request.method == "POST":
        # Create instances of both ticket and review forms with the submitted data
        ticket_form = forms.TicketForm(request.POST, request.FILES)
        review_form = forms.ReviewForm(request.POST)

        if ticket_form.is_valid() and review_form.is_valid():
            ticket = ticket_form.save(commit=False)
            # Set the user for the ticket
            ticket.user = request.user
            ticket.save()

            # Save the review without committing to the database
            review = review_form.save(commit=False)
            # Set the user and ticket for the review
            review.user = request.user
            review.ticket = ticket
            review.save()

            messages.success(request, "Critique créé avec succès.")
            return redirect("blog:posts")
        else:
            messages.error(
                request,
                "Erreur lors de la création une critique. Veuillez vérifier le formulaire.",
            )
    else:
        # If the request is a GET request (the user is loading the page),
        # create instances of empty ticket and review forms
        ticket_form = forms.TicketForm()
        review_form = forms.ReviewForm()

    # Pass the ticket and review forms to the template
    context = {
        "ticket_form": ticket_form,
        "review_form": review_form,
    }

    return render(request, "blog/create_review.html", context)


@login_required
def response_review(request, ticket_id):
    ticket = Ticket.objects.get(id=ticket_id)

    if request.method == "POST":
        review_form = forms.ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.ticket = ticket
            review.user = request.user
            review.save()

            messages.success(request, "Critique créée avec succès.")
            return redirect("blog:flux")
        else:
            messages.error(
                request,
                "Erreur lors de la création d'une critique. Veuillez vérifier le formulaire.",
            )
    else:
        review_form = forms.ReviewForm()

    context = {
        "review_form": review_form,
        "ticket": ticket,
    }

    return render(request, "blog/response_review.html", context)


def model_type(value):
    return type(value).__name__


@login_required
def update_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)

    if request.user != ticket.user:
        return redirect("blog:flux")

    if request.method == "POST":
        # If the request method is POST, process the form data
        form_ticket = forms.TicketForm(request.POST, instance=ticket)

        if form_ticket.is_valid():
            # Save the form data excluding the image field
            updated_ticket = form_ticket.save(commit=False)

            # Check if a new image was uploaded
            if "image" in request.FILES:
                updated_ticket.image = request.FILES["image"]

            updated_ticket.save()

            messages.success(request, "Votre ticket est mis à jour avec succès.")

            # Redirect the user to the 'posts' page after successful ticket update
            return redirect("blog:posts")
        else:
            messages.error(
                request,
                "Erreur lors de la mise à jour du ticket. Veuillez vérifier le formulaire.",
            )
    else:
        # If the request method is GET, create a form instance with the current ticket data
        form_ticket = forms.TicketForm(instance=ticket)

    # Create a context dictionary containing the ticket and the form
    context = {
        "ticket": ticket,
        "form_ticket": form_ticket,
    }

    return render(request, "blog/update_ticket.html", context)


@login_required
def update_review(request, review_id):
    review = get_object_or_404(Review, id=review_id)

    # Check if the current user is the owner of the review
    if request.user != review.user:
        return redirect("blog:flux")

    # If the request method is POST, it means the form is submitted for updating the review
    if request.method == "POST":
        # Create a ReviewForm instance with the submitted POST data and the existing review object
        form_review = forms.ReviewForm(request.POST, instance=review)

        if form_review.is_valid():
            form_review.save()
            messages.success(request, "Votre review est mise à jour avec succès")
            return redirect("blog:posts")
    else:
        # If the request method is GET, it means the user is accessing the page to view the form
        # Create a ReviewForm instance with the existing review object to pre-fill the form
        form_review = forms.ReviewForm(instance=review)

    # Prepare the context data to pass to the template
    context = {
        "review": review,
        "form_review": form_review,
    }

    return render(request, "blog/update_review.html", context)


@login_required
def delete_ticket(request, ticket_id):
    # Get the ticket object with the given ticket_id or return a 404 error if not found
    ticket = get_object_or_404(Ticket, id=ticket_id)

    # Check if the current user is the owner of the ticket
    if request.user != ticket.user:
        return redirect("blog:flux")

    ticket.delete()

    messages.success(request, "Votre ticket est supprimée avec succès")

    return redirect("blog:posts")


@login_required
def delete_review(request, review_id):
    # Get the review object with the given review_id or return a 404 error if not found
    review = get_object_or_404(Review, id=review_id)

    # Check if the current user is the owner of the review
    if request.user != review.user:
        return redirect("blog:flux")

    # If the user is the owner of the review, proceed to delete it
    review.delete()

    messages.success(request, "Votre review est supprimée avec succès")

    return redirect("blog:posts")


@login_required
def subscriptions(request):
    # Create a form instance for following other users
    subscriptions_form = forms.FollowUserForm()

    # Get the objects that represent the users that the current user is following
    subscriptions_objects = UserFollows.objects.filter(user=request.user)

    # Get the objects that represent the users who are following the current user
    subscribers_objects = UserFollows.objects.filter(followed_user=request.user)

    # Prepare the context with the subscriptions and following users
    context = {
        "subscriptions_form": subscriptions_form,
        "subscriptions_objects": subscriptions_objects,
        "subscribers_objects": subscribers_objects,
    }

    # Redirect the user to the 'subscriptions' page
    return render(request, "blog/subscriptions.html", context)


@login_required

LITRevu/blog/templates/blog/create_review.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
    <div class= "col-md-6 shadow p-4 mt-4 mb-5 bg-body rounded mx-auto">
        <h3 class="text-center">Créer une critique</h3>
        <div class="form border border-success d-flex justify-content-center ">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <p class='mt-1 fw-bolder'>À propos de ce livre:</p>
                <div class='mb-3 mt-3'>
                    {% bootstrap_form ticket_form %}
                </div>
                <hr>
                <p class='mt-1 fw-bolder'>Ma critique:</p>
                <div class="mb-3 mt-3">
                    {% bootstrap_field review_form.headline %}
                </div>

                <div class="mb-3 mt-3 form-check-inline">
                    <!-- Modify this line to display the radio buttons inline -->
                    <div class="mb-3">
                        <label class="form-label me-3">Rating:</label>
                        {% for radio in review_form.rating %}
                            <label class="form-check-label me-3">
                                {{ radio.tag }}
                                {{ radio.choice_label }}
                            </label>
                        {% endfor %}
                    </div>
                </div>

                <div class="mb-3 mt-3">
                    {% bootstrap_field review_form.body %}
                </div>
                <div class="d-flex justify-content-center mb-4 mt-3">
                    {% bootstrap_button button_type="submit" content="Envoyer" %}
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

LITRevu/blog/templates/blog/create_ticket.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
    <div class= "col-md-6 shadow p-4 mt-4 mb-5 bg-body rounded mx-auto">
        <h3 class="text-center">Créer un ticket</h3>
        <div class="form border border-success d-flex justify-content-center ">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3 mt-3">
                    {% bootstrap_form form %}
                </div>
                <div class="mb-4 text-center">
                    {%bootstrap_button button_type='submit' content='Envoyer' %}
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

LITRevu/blog/templates/blog/flux.html
{% extends 'base.html' %}

{% block content %}
    {% include 'blog/message.html' %}
    {% include 'blog/flux_posts_content.html' with content_title="Flux" %}
{% endblock content %}

LITRevu/blog/templates/blog/message.html
{% if messages %}
    {% for message in messages %}
        <div class="mt-2 alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message.message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

LITRevu/blog/templates/blog/posts.html
{% extends 'base.html' %}

{% block content %}
    {% include 'blog/message.html' %}
    {% include 'blog/flux_posts_content.html' with content_title="Vos posts" %}

{% endblock content %}

LITRevu/blog/templates/blog/response_review.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

    <div class="col-md-6 shadow p-4 mt-4 mb-5 bg-body rounded mx-auto">
        <h3 class="text-center">Créer une critique</h3>
        <div class="form border border-success d-flex justify-content-center">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <p class='mt-1 fw-bolder'>À propos de ce livre:</p>
                <div class='mb-3 mt-3'>
                    <div class="mb-3">
                        <label class="form-label" for="id_title">Title:</label>
                        <input class="form-control" type="text" placeholder='{{ticket.title}}' disabled>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="id_title">Description:</label>
                        <input class="form-control" type="text" placeholder='{{ticket.description}}' disabled>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="id_title">Image:</label>
                        <div class="text-center">
                            <img class="img-thumbnail rounded " src="{{ticket.image.url}}" width="300" height="200" alt="{{ item.title }}"/>
                        </div>
                    </div>
                    {% comment %} {% bootstrap_form ticket_form %} {% endcomment %}
                </div>
                <hr>
                <p class='mt-1 fw-bolder'>Ma critique:</p>
                <div class="mb-3 mt-3">
                    {% bootstrap_field review_form.headline %}
                </div>

                <div class="mb-3 mt-3 form-check-inline">
                    <div class="mb-3">
                        <label class="form-label me-3">Rating:</label>
                        {% for radio in review_form.rating %}
                            <label class="form-check-label me-3">
                                {{ radio.tag }}
                                {{ radio.choice_label }}
                            </label>
                        {% endfor %}
                    </div>
                </div>

                <div class="mb-3 mt-3">
                    {% bootstrap_field review_form.body %}
                </div>
                <div class="d-flex justify-content-center mb-4 mt-3">
                    {% bootstrap_button button_type="submit" content="Envoyer" %}
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

LITRevu/blog/templates/blog/search_user.html
{% extends 'base.html' %}

{% block content %}

    {% include 'blog/message.html' %}

    <!-- Search form to follow other users -->
    <h4 class="text-center mt-3">Rechercher un utilisateur:</h4>
    <form method="post" class="d-flex mb-5 " role="search" action="{% url 'flux:search-user' %}">
        {% csrf_token %}
        <input class="form-control me-2" name="searched" type="search" placeholder="Rechercher un utilisateur" aria-label="Search">
        <button class="btn btn-outline-secondary" type="submit">Rechercher</button>
    </form>

    {% if searched %}
    <h4 class="text-center mt-3">Vous avez recherché l'utilisateur <span class="text-danger">{{ searched }}</span></h4>
    <hr>
    <!-- Table for showing subscriptions -->
    <h4 class="text-center">Utilisatrices:</h4>
    <table class="table table-striped mb-5">
        <thead>
            <tr>
                <th>Utilisateur</th>
                <th class="text-end">Action</th>
            </tr>
        </thead>
    {% for user in users %}
        </tbody>
            <tr>
                <td>{{ user }}</td>
                <td class="text-end">
                    {% if user.id in following_users %}
                        <!-- Show "Désabonner" button if the user is already followed -->
                        <a href="{% url 'blog:unsubscribe' user.id %}" class="btn btn-danger">Désabonner</a>
                    {% else %}
                        <!-- Show "S'abonner" button if the user is not followed -->
                        <a href="{% url 'blog:subscribe' user.id %}" class="btn btn-primary">S'abonner</a>
                    {% endif %}
                </td>
            </tr>
        </tbody>
    {% endfor %}
    </table>

    {% if users|length == 0 %}
        <h4 class="text-center mt-3 text-danger">Aucun utilisateur trouvé avec ce nom d'utilisateur.</h4>
    {% endif %}

    {% else %}
        <h4 class="text-center mt-3 text-danger">Hé! Vous avez oublié de rechercher un utilisateur ...</h4>
        <hr>
    {% endif %}

{% endblock content %}

LITRevu/blog/templates/blog/subscriptions.html
{% extends 'base.html' %}

{% block content %}

    {% include 'blog/message.html' %}

    <!-- Search form to follow other users -->
    <h4 for="search_user" class="text-center mt-3">Rechercher un utilisateur:</h4>
    <form method="post" class="d-flex mb-5 " role="search" action="{% url 'flux:search-user' %}">
        {% csrf_token %}
        <input class="form-control me-2" name="searched" type="search" placeholder="Rechercher un utilisateur" aria-label="Search">
        <button class="btn btn-outline-secondary" type="submit">Rechercher</button>
      </form>

    <!-- Table for showing subscriptions -->
    <h4 class="text-center">Abonnements:</h4>
    <table class="table table-striped mb-5">
        <thead>
            <tr>
                <th>Utilisateur</th>
                <th class="text-end">Action</th>
            </tr>
        </thead>
        <tbody>
        {% for subscription in subscriptions_objects %}
            <tr>
                <td>{{ subscription.followed_user }}</td>
                <td class="text-end">
                    <a href="{% url 'blog:unsubscribe' subscription.followed_user.id %}" class="btn btn-danger">Désabonner</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <!-- Table for showing subscribers -->
    <h4 class="text-center">Abonnés:</h4>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Utilisateur</th>
            </tr>
        </thead>
        <tbody>
            {% for subscriber in subscribers_objects %}
            <tr>
                <td>{{ subscriber.user }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

LITRevu/blog/templates/blog/ticket_review_footer.html
{% load django_bootstrap5 %}

<div class="card-footer text-muted">
    <div class="d-flex bd-highlight">
        {% if not is_review and ticket.review_set.all.count == 0 %}
            <div class="text-start flex-grow-1">
                <a href="{% url 'flux:response-review' item.id %}">
                    {% bootstrap_button button_type="submit" button_class="btn-outline-success" content="Créer une critique" %}
                </a>
            </div>
        {% endif %}
        <div class="flex-grow-1"></div>
        {% if request.user == item.user and is_review %}
            <div class="">
                <a href="{% url 'flux:update-review' item.id %}">
                    {% bootstrap_button button_type="submit" button_class="btn-outline-success" content="Modifier" %}
                </a>
                <a href="{% url 'flux:delete-review' item.id %}">
                    {% bootstrap_button button_class="btn-outline-danger" content="Supprimer" %}
                </a>
            </div>
        {% elif request.user == item.user and not is_review %}
            <div class="">
                <a href="{% url 'flux:update-ticket' item.id %}">
                    {% bootstrap_button button_type="submit" button_class="btn-outline-success" content="Modifier" %}
                </a>
                <a href="{% url 'flux:delete-ticket' item.id %}">
                    {% bootstrap_button button_class="btn-outline-danger" content="Supprimer" %}
                </a>
            </div>
        {% endif %}
    </div>
</div>

LITRevu/blog/templates/blog/ticket_review_item.html
{% load django_bootstrap5 %}

<div class="card text-center col-md-auto mb-4 bg-light bg-opacity-25">

    <div class="card-header alert {% if is_review %}alert-info{% else %}alert-success{% endif %} p-1 mb-0">
        {% if ticket.review_set.all.count > 0 %}
            <span>Cette ticket a déjà une critique.</span>
        {% else %}
            {% if request.user == item.user %}
                <span>Vous avez {% if is_review %}publié une critique{% else %}demandé une critique{% endif %}</span>
            {% else %}
                <span>{{item.user.username}} a {% if is_review %}publié une critique{% else %}demandé une critique{% endif %}</span>
            {% endif %}
        {% endif %}
    </div>
        
    <div class="card-body">
        <div class="card-title d-flex justify-content-between">
            <p class="fw-bolder text-decoration-underline"><i class="bi bi-person-circle p-1"></i>{{ item.user }}</p>
            <p>{{ item.time_created|date:'H:i, d-m-Y' }}</p>
        </div>

        <div class="card-text">
            {% if not is_review %}
                <div class="text-start  mb-3">
                    <p class="fst-italic fw-bolder">Titre: <span class ="fst-italic fw-normal">{{ item.title }}</span></p>
                    <p class="fw-bolder">Description: <span class ="fw-normal">{{ item.description }}</span></p>
                    <div class="text-center">
                        {% if item.image %}
                            <img class="img-thumbnail rounded bg-light bg-opacity-25" src="{{ item.image.url }}" width="300" height="200" alt="{{ item.title }}">
                        {% else %}
                            <p>No image available</p>
                        {% endif %}
                    </div>
                </div>
            {% endif %}

            {% if is_review %}
                <div class="d-flex justify-content-between">
                    <p><span class="fw-bolder">Titre: </span>{{ item.headline }}</p>
                    <div class="mx-auto">
                        {% for star in "*****" %}
                            {% if forloop.counter <= item.rating %}
                                <i class="bi bi-star-fill"></i>
                            {% else %}
                                <i class="bi bi-star"></i>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>

                <div>
                    <p class="fw-bolder text-start">Description: <span class ="fw-normal">{{ item.body }}</span></p>
                </div>

                <div class="col-md-8 shadow p-4 mt-4 mb-3 bg-body rounded mx-auto bg-light bg-opacity-50">
                    <div class="card-title d-flex justify-content-between">
                        <p class="fw-bolder text-decoration-underline"><i class="bi bi-person-circle p-1"></i>{{ item.ticket.user }}</p>
                        <p>{{ item.ticket.time_created|date:'H:i, d-m-Y' }}</p>
                    </div>
                    <p class="fst-italic fw-bolder">Titre: <span class ="fst-italic fw-normal">{{ item.ticket.title }}</span></p>
                    <p class="fw-bolder">Description: <span class ="fw-normal"> {{ item.ticket.description }}</span></p>
                    <div class="text-center">
                        {% if item.ticket.image %}
                            <img class="img-book img-thumbnail rounded bg-light bg-opacity-25" src="{{ item.ticket.image.url }}" width="300" height="200" alt="{{ item.ticket.title }}">
                        {% else %}
                            <p>No image available</p>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

    <div class="card-footer text-muted">
        <div class="d-flex bd-highlight ">
            {% if not is_review and ticket.review_set.all.count == 0 %}
                <div class="text-start flex-grow-1">
                    <a href="{% url 'flux:response-review' item.id %}">
                        {% bootstrap_button button_type="submit" button_class="btn-outline-success" content="Créer une critique" %}
                    </a>
                </div>
            {% endif %}
            <div class="flex-grow-1"></div>
            {% if request.user == item.user and is_review %}
                <div class="">
                    <a href="{% url 'flux:update-review' item.id %}">
                        {% bootstrap_button button_type="submit" button_class="btn-outline-success" content="Modifier" %}
                    </a>
                    <a href="{% url 'flux:delete-review' item.id %}">
                        {% bootstrap_button button_class="btn-outline-danger" content="Supprimer" %}
                    </a>
                </div>
            {% elif request.user == item.user and not is_review %}
            <div class="">
                <a href="{% url 'flux:update-ticket' item.id %}">
                    {% bootstrap_button button_type="submit" button_class="btn-outline-success" content="Modifier" %}
                </a>
                <a href="{% url 'flux:delete-ticket' item.id %}">
                    {% bootstrap_button button_class="btn-outline-danger" content="Supprimer" %}
                </a>
            </div>
            {% endif %}
        </div>
    </div>
</div>